# SEO keywords and description for your site.
keywords = "hugo, tailwind, tailwindcss, hugo theme, hugo theme tailwind"
subtitle = ""

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"
toc = true
[header]
  logo = "logo.png"

[footer]
  since = 2022
  poweredby = false

# giscus is comments system powered by GitHub Discussions
# generate configurations from https://giscus.app/
[giscus]
  enabled = true
  repo = "v-vietlq4/v-vietlq4.github.io"
  repoID = "R_kgDOHKi_mg"
  category = "Announcements"
  categoryID = "DIC_kwDOHKi_ms4Cc79f"
  mapping = "pathname"
  strict = "1"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lang = "en"

[social_media]
  [[social_media.items]]
    enabled = true
    title = 'Facebook'
    icon = 'brand-facebook'
    link = 'https://www.facebook.com/vietawake'

  [[social_media.items]]
    enabled = true
    title = 'Twitter'
    icon = 'brand-x'
    link = 'https://twitter.com/vietlq_awake'

  [[social_media.items]]
    enabled = true
    title = 'Instagram'
    icon = 'brand-instagram'
    link = 'https://www.instagram.com/'

  [[social_media.items]]
    enabled = true
    title = 'LinkedIn'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/in/vietawake'

  [[social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/v-vietlq4'
